PORTNAME=	mustermann
PORTVERSION=	3.1.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Library implementing patterns that behave like regular expressions
WWW=		https://sinatrarb.com/mustermann/ \
		https://github.com/sinatra/mustermann/tree/master/mustermann

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gem

NO_ARCH=	yes

.include <bsd.port.mk>
