PORTNAME=      xonix
PORTVERSION=   1.5
CATEGORIES=    games
MASTER_SITES=  https://github.com/dl8dtl/xonix/archive/refs/tags/
DISTNAME=      v${PORTVERSION}
DIST_SUBDIR=   xonix

MAINTAINER=    joerg@FreeBSD.org
COMMENT=       Try to win land without colliding with "flyers" and "eaters"
WWW=           https://github.com/dl8dtl/xonix

LICENSE=       BSD2CLAUSE

USES=          imake
WRKSRC=        ${WRKDIR}/xonix-${PORTVERSION}
USE_XORG=      x11 xaw xorgproto

.include <bsd.port.mk>
