--- pyproject.toml.orig	2026-04-28 05:17:17 UTC
+++ pyproject.toml
@@ -1,6 +1,6 @@ build-backend = "uv_build"
 [build-system]
 build-backend = "uv_build"
-requires = ["uv_build>=0.10.0,<0.11.0"]
+requires = ["uv_build>=0.10.0"]
 
 [project]
 name = "cucumber-tag-expressions"
