PORTNAME=	types-python-dateutil
DISTVERSION=	2.9.0.20260323
CATEGORIES=	devel python
MASTER_SITES=	PYPI
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	types_python_dateutil-${DISTVERSION}

MAINTAINER=	yuri@FreeBSD.org
COMMENT=	Typing stubs for python-dateutil
WWW=		https://github.com/python/typeshed

LICENSE=	APACHE20

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
